name: crawl

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ startsWith(github.event.head_commit.message, 'docs') }}
    name: crawl
    env:
      API_KEY: ${{secrets.ALGOLIA_API_KEY}}
      APPLICATION_ID: GERZE019PN
    runs-on: ubuntu-latest
    container: algolia/docsearch-scraper
    steps:
      - name: Wait for Netlify deployment
        uses: whatnick/wait-action@master
        with:
          time: '50s'
      - uses: actions/checkout@v4
      - run: 'sudo apt-get install -y jq'
      - run: 'echo "CONFIG=$(cat docs/.algolia/config.json | jq -r tostring)" >> $GITHUB_ENV'
      - run: "cd /root && pipenv install"
      - run: "cd /root && pipenv run python -m src.index"
